services:
  - type: web
    name: ai-news-aggregator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: ai-news-mongodb
    databaseName: ai_news_aggregator
    user: ai_news_user